BookingTickets/Controllers/AccountController.cs
using BookingTickets.Model;
using BookingTickets.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookingTickets.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService _userService;
        private readonly IViewModelsService _viewModelsService;

        public AccountController(IUserService userService, IViewModelsService viewModelsService)
        {
            _userService = userService ?? throw new ArgumentNullException(nameof(userService));
            _viewModelsService = viewModelsService ?? throw new ArgumentNullException(nameof(viewModelsService));
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginData loginData, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                UserResult loginResult = await _userService.LoginAsync(loginData);
                if (loginResult.Success)
                {
                    return Redirect(returnUrl ?? "/");
                }

                ModelState.AddModelError("Email", "Неверный логин или пароль");
            }
            return View(_viewModelsService.GetLoginViewModel(loginData));
        }

        [AllowAnonymous]
        public IActionResult Registration()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration(RegisterUserData registerData)
        {
            if (ModelState.IsValid)
            {
                UserResult registerResult = await _userService.RegisterNewUserAsync(registerData);
                if (registerResult.Success)
                {
                    return RedirectToAction(nameof(Login));
                }

                foreach (UserError error in registerResult.Errors)
                    ModelState.AddModelError("", error.Message);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _userService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }
    }
}

BookingTickets/Controllers/CartController.cs
using BookingTickets.Model;
using BookingTickets.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookingTickets.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IViewModelsService _viewModelsService;

        public CartController(ICartService cartService, IViewModelsService viewModelsService)
        {
            _cartService = cartService ?? throw new ArgumentNullException(nameof(cartService));
            _viewModelsService = viewModelsService ?? throw new ArgumentNullException(nameof(viewModelsService));
        }

        public IActionResult Index(string returnUrl)
        {
            return View(_viewModelsService.GetCartViewModel(returnUrl));
        }

        [HttpPost]
        //TODO: Заменить на другое действие.
        public async Task<IActionResult> UpdateItems([FromBody] UpdateCartItemsModel updateCartItemsModel)
        {
            if (ModelState.IsValid)
            {
                foreach (CartItem cartItem in updateCartItemsModel.Items)
                {
                    await _cartService.UpdateItemAsynс(cartItem);
                }

                return Ok();
            }

            return BadRequest(ModelState);
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(Guid ticketId, string returnUrl)
        {
            await _cartService.AddItemAsync(new CartItem(ticketId, 1));
            return Redirect(returnUrl ?? "/");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItem(Guid ticketId, string returnUrl)
        {
            await _cartService.RemoveItemAsync(ticketId);
            return RedirectToAction(nameof(Index), new { returnUrl });
        }
    }
}

BookingTickets/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookingTickets.Service;
using Microsoft.AspNetCore.Mvc;

namespace BookingTickets.Controllers
{
    public class OrderController : Controller
    {
        private readonly IViewModelsService _viewModelsService;
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService, IViewModelsService viewModelsService)
        {
            _orderService = orderService ?? throw new ArgumentNullException(nameof(orderService));
            _viewModelsService = viewModelsService 
                ?? throw new ArgumentNullException(nameof(viewModelsService));
        }

        [ActionName("Checkout")]
        [HttpGet]
        public IActionResult CheckoutPage()
        {
            return View(_viewModelsService.GetOrderCheckoutViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout()
        {
            await _orderService.CreateOrderAsync();
            return RedirectToAction(nameof(Complete));
        }

        public IActionResult Complete()
        {
            return View();
        }
    }
}

BookingTickets/Controllers/ProfileController.cs
using BookingTickets.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookingTickets.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IViewModelsService _viewModelsService;

        public ProfileController(IViewModelsService viewModelsService)
        {
            _viewModelsService = viewModelsService ?? throw new ArgumentNullException(nameof(viewModelsService));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _viewModelsService.GetProfileViewModelAsync());
        }
    }
}

BookingTickets/Controllers/TicketController.cs
using BookingTickets.Converter;
using BookingTickets.EFCore.Domain;
using BookingTickets.EFCore.Repository;
using BookingTickets.Service;
using BookingTickets.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using BookingTickets.Model;
using Microsoft.AspNetCore.Authorization;

namespace BookingTickets.Controllers
{
    public class TicketController : Controller
    {
        private readonly IRepository<Ticket> _repository;
        private readonly IViewModelsService _viewModelsService;
        private readonly TicketConverter _ticketConverter;

        public TicketController(
            IRepository<Ticket> repository,
            IViewModelsService viewModelsService,
            TicketConverter ticketConverter
        )
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _viewModelsService = viewModelsService 
                ?? throw new ArgumentNullException(nameof(viewModelsService));
            _ticketConverter = ticketConverter 
                ?? throw new ArgumentNullException(nameof(ticketConverter));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(TicketIndexModel ticketIndexModel)
        {
            return View(await _viewModelsService.GetTicketsViewModelAsync(ticketIndexModel));
        }

        [AllowAnonymous]
        public async Task<ActionResult> Edit(Guid id)
        {
            Ticket ticket = await _repository.GetByIdAsync(id);
            return View(await _viewModelsService.GetTicketEditViewModelAsync(ticket));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.ADMIN_ROLE_NAME)]
        public async Task<ActionResult> Edit(Ticket ticket)
        {
            await _repository.UpdateAsync(ticket);
            return RedirectToAction("Index");
        }

        [ActionName("Delete")]
        [Authorize(Roles = RoleConstants.ADMIN_ROLE_NAME)]
        public async Task<ActionResult> DeletePage(Guid id)
        {
            Ticket ticket = await _repository.GetByIdAsync(id);
            return View(_ticketConverter.ConvertToModel(ticket));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleConstants.ADMIN_ROLE_NAME)]
        public async Task<ActionResult> Delete(Guid id)
        {
            await _repository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

BookingTickets/Views/Cart/Index.cshtml
@model CartViewModel

@{
    ViewData["Title"] = "Корзина";
    ViewData["returnUrl"] = Model.ReturnUrl;
}

@section Scripts {
    <script src="~/dist/cart.js"></script>
}

<div>
    <h3>Корзина</h3>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div id="CartItemsContainer">
        <table id="CartItems">
            <thead>
                <tr>
                    <th>Тип</th>
                    <th>Описание</th>
                    <th>Время</th>
                    <th>Количество</th>
                    <th>Сумма</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.CartItems.Count; ++i)
                {
                    CartItemModel cartItem = Model.CartItems[i];
                    <tr id="CartItemRow-@cartItem.Ticket.Id">
                        <td>@cartItem.Ticket.Type.Name</td>
                        <td>@cartItem.Ticket.Description</td>
                        <td>@cartItem.Ticket.EventTime</td>
                        <td>
                            <form>
                                <input asp-for="CartItems[i].Quantity" class="ticket-quantity" data-price="@cartItem.Ticket.Price" data-ticketid="@cartItem.Ticket.Id"
                                    data-val-range="@("Количество билетов должно быть в диапазоне от 1 до " + @cartItem.Ticket.Quantity)" data-val-range-min="1" data-val-range-max="@cartItem.Ticket.Quantity"/>
                                <span asp-validation-for="CartItems[i].Quantity" class="text-danger"></span>
                            </form>
                        </td>
                        <td class="ticket-amount">@cartItem.Amount</td>
                        <td>
                            <form asp-action="RemoveItem">
                                <input asp-for="ReturnUrl" type="hidden" />
                                <input type="hidden" name="ticketId" value="@cartItem.Ticket.Id" />
                                <input type="submit" value="Удалить" class="waves-effect waves-light btn" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-controller="Order" asp-action="Checkout" class="waves-effect waves-light btn">Подтвердить заказ</a>
        <a href="@Model.ReturnUrl" class="waves-effect waves-light btn">Назад</a>
    </div>
</div>

BookingTickets/Views/Order/Checkout.cshtml
@model OrderCheckoutViewModel

@{
    ViewData["Title"] = "Подтверждение заказа";
}

<div>
    <h3>Ваш заказ:</h3>
    <div>
        <table>
            <thead>
            <tr>
                <th>Тип</th>
                <th>Описание</th>
                <th>Время</th>
                <th>Количество</th>
                <th>Сумма</th>
            </tr>
            </thead>
            <tbody>
                @foreach (CartItemModel cartItem in Model.CartItems)
                {
                    <tr id="CartItemRow-@cartItem.Ticket.Id">
                        <td>@cartItem.Ticket.Type.Name</td>
                        <td>@cartItem.Ticket.Description</td>
                        <td>@cartItem.Ticket.EventTime</td>
                        <td>@cartItem.Ticket.Quantity</td>
                        <td>@cartItem.Amount</td>
                    </tr>
                }
            </tbody>
        </table>
        
        <form asp-action="Checkout">
            <input type="submit" value="Подтвердить" class="waves-effect waves-light btn"/>
        </form>
    </div>
</div>

BookingTickets/Views/Order/Complete.cshtml
@{
    ViewData["Title"] = "Complete";
}

<h3>Complete</h3>

<div>
    Ваш заказ успешно оформлен.
</div>

BookingTickets/Views/Shared/Ticket.cshtml
@model TicketViewModel

@{
    string id = Model.Ticket.Id.ToString();
    string ticketContainerId = "TicketContainer-" + id;
    string ticketInfoContainerId = "TicketInfoContainer-" + id;
    string ticketActionsContainerId = "TicketActionsContainer-" + id;
    string quantity = Model.Ticket.Quantity > 0 ? Model.Ticket.Quantity.ToString() : "Нет в наличии";

    <div id="@ticketContainerId" class="collection-item">
        <div id="@ticketInfoContainerId" class="ticketColumns">
            <div style="width:50%">@Model.Ticket.Description</div>
            <div style="width:25%">@Model.Ticket.Price</div>
            <div style="width:25%">@quantity</div>
        </div>
        <div id="@ticketActionsContainerId">
            <form asp-controller="Cart" asp-action="AddItem">
                <a class="waves-effect waves-light btn" asp-controller="Ticket" asp-action="Edit" asp-route-id="@id" asp-route-returnUrl="@Model.ReturnUrl">Просмотр</a>
                @if (Model.CanEdit)
                {
                    <a class="waves-effect waves-light btn" asp-controller="Ticket" asp-action="Delete" asp-route-id="@id" asp-route-returnUrl="@Model.ReturnUrl">Удалить</a>
                }
                @if (Model.Ticket.Quantity > 0)
                {
                    <input type="hidden" asp-for="Ticket.Id" name="ticketId">
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                    <input type="submit" class="waves-effect waves-light btn" value="В корзину" />
                }
            </form>
            </div>
    </div>
}

BookingTickets/Views/Shared/User.cshtml
@model LoginViewModel

@{ 
    
}

BookingTickets/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - test</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - test</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BookingTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment exclude="Development">
        <link rel="stylesheet" href="~/dist/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container">
        <nav>
            <div class="nav-wrapper">
                <ul class="left hide-on-med-and-down">
                    <li><a asp-controller="Ticket" asp-action="Index">Главная</a></li>
                </ul>
                <ul class="right hide-on-med-and-down">
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a class="dropdown-button" href="#" data-activates="UserMenuDropdown" data-beloworigin="true">@User.Identity.Name</a>

                                <ul id="UserMenuDropdown" class="dropdown-content">
                                    <li><a asp-controller="Profile" asp-action="Index">Профиль</a></li>
                                    <li id="LogoutButton"><span>Выход</span></li>
                                </ul>
                                <form asp-action="Logout" asp-controller="Account" id="LogoutFrom"></form>
                            </li>
                            <li>
                                <a asp-controller="Cart" asp-action="Index" asp-route-returnUrl="@ViewData["returnUrl"]">Корзина</a>
                            </li>
                        }
                        else
                        {
                            <li><a asp-controller="Account" asp-action="Login">Войти</a></li>
                            <li><a asp-controller="Account" asp-action="Registration">Регистрация</a></li>
                        }
                    }
                </ul>
            </div>
        </nav>
        <div id="BodyContainer" class="body-container">
            @RenderBody()
        </div>
    </div>
    
    <script src="~/dist/bundle.js" asp-append-version="true"></script>
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    @RenderSection("Scripts", required: false)
</body>
</html>

BookingTickets/Views/Ticket/Delete.cshtml
@model TicketModel

@{
    ViewData["Title"] = "Удаление";
}

<h3>Вы действительно хотите удалить этот билет?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input asp-for="Id" type="hidden" />
        <input type="submit" class="btn btn-default" value="ОК" />
        <a asp-action="Index" class="waves-effect waves-light btn">Назад</a>
    </form>
</div>

BookingTickets/Views/Ticket/Edit.cshtml
@model TicketEditViewModel

@{
    ViewData["Title"] = "Edit";
    IEnumerable<SelectListItem> ticketTypesSelectList = 
        Model.TicketTypes.ConvertToSelectListItems(Model.Ticket?.Type.Value, elem => elem.Id, elem => elem.Name);
}

<h2>Edit</h2>

<h4>Ticket</h4>
<hr />
<div>
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ticket.Description" class="control-label"></label>   
                <input asp-for="Ticket.Description" readonly="@(!Model.CanEdit)" class="form-control" />
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Type.Value" class="control-label"></label>
                <select asp-for="Ticket.Type.Value" asp-items="@ticketTypesSelectList" disabled="@(!Model.CanEdit)" name="TypeId" class="browser-default"></select>
                <span asp-validation-for="Ticket.Type.Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Price" class="control-label"></label>
                <input asp-for="Ticket.Price" readonly="@(!Model.CanEdit)" class="form-control" />
                <span asp-validation-for="Ticket.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Quantity" class="control-label"></label>
                <input asp-for="Ticket.Quantity" readonly="@(!Model.CanEdit)" class="form-control" />
                <span asp-validation-for="Ticket.Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.EventTime" class="control-label"></label>
                <input asp-for="Ticket.EventTime" readonly="@(!Model.CanEdit)" class="form-control" />
                <span asp-validation-for="Ticket.EventTime" class="text-danger"></span>
            </div>
            <input asp-for="Ticket.Id" type="hidden" class="form-control" />
            <div class="form-group">
                @if (Model.CanEdit)
                {
                    <input type="submit" value="Сохранить" class="btn btn-default"/>
                }
                <a asp-action="Index" class="waves-effect waves-light btn">Назад</a>
            </div>
        </form>
    </div>
</div>

BookingTickets/Views/Ticket/Index.cshtml
@using System.Runtime.InteropServices.ComTypes
@model TicketsViewModel

@{
    ViewData["Title"] = "Билеты";
    ViewData["returnUrl"] = Model.ReturnUrlToHome;
    Dictionary<string, object> routeValues = new Dictionary<string, object>
    {
        ["Description"] = Model.TicketIndexModel.Description,
        ["EventTimeFor"] = Model.TicketIndexModel.EventTimeFor,
        ["EventTimeTo"] = Model.TicketIndexModel.EventTimeTo,
        ["PriceFor"] = Model.TicketIndexModel.PriceFor,
        ["PriceTo"] = Model.TicketIndexModel.PriceTo,
        ["QuantityFor"] = Model.TicketIndexModel.QuantityFor,
        ["QuantityTo"] = Model.TicketIndexModel.QuantityTo,
        ["TypeId"] = Model.TicketIndexModel.TypeId
    };

    List<SelectListItem> typesSelectListItems = new List<SelectListItem>
    {
        new SelectListItem { Value = "", Text = "Выберите тип", Selected = true }
    };
    typesSelectListItems.AddRange(Model.TicketTypes.ConvertToSelectListItems(Model.TicketIndexModel?.TypeId, elem => elem.Id, elem => elem.Name));

}

<div id="MainContainer">
    <div id="LeftMenuContainer" class="left-menu-container">
        <div id="CategoryListContainer">
            <div class="collection">
                @foreach (TicketTypeModel ticketType in Model.TicketTypes)
                {
                    string activeClass = ticketType.Id == Model.TicketIndexModel?.TypeId ? "active" : null;
                    <a asp-action="Index" asp-route-typeId="@ticketType.Id" asp-route-count="@Model.SelectedItemsPerPage" class="collection-item @activeClass">@ticketType.Name</a>
                }
            </div>
        </div>
        <div id="SearchContainer">
            <form asp-action="Index" method="get">
                <input asp-for="TicketIndexModel.Count" type="hidden" />
                <div class="form-group">
                    <label asp-for="TicketIndexModel.TypeId" class="control-label"></label>
                    <select asp-for="TicketIndexModel.TypeId" asp-items="@typesSelectListItems" class="form-control browser-default"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.Description" class="control-label">Описание</label>
                    <input asp-for="TicketIndexModel.Description" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.PriceFor" class="control-label"></label>
                    <input asp-for="TicketIndexModel.PriceFor" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.PriceTo" class="control-label"></label>
                    <input asp-for="TicketIndexModel.PriceTo" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.QuantityFor" class="control-label"></label>
                    <input asp-for="TicketIndexModel.QuantityFor" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.QuantityTo" class="control-label"></label>
                    <input asp-for="TicketIndexModel.QuantityTo" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.EventTimeFor" class="control-label"></label>
                    <input asp-for="TicketIndexModel.EventTimeFor" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="TicketIndexModel.EventTimeTo" class="control-label"></label>
                    <input asp-for="TicketIndexModel.EventTimeTo" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Поиск" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
    <div id="MainContentContainer" class="main-content-container">
        <div id="HeaderContainer">
            @if (Model.CanEditTickets)
            {
                <a class="waves-effect waves-light btn" asp-controller="Ticket" asp-action="Edit" asp-route-id="@Guid.Empty">Добавить билет</a>
            }
        </div>
        <div id="ContentContainer">
            <div id="TicketsContainer">
                <div id="TicketsContentWrapContainer"></div>
                <div id="TicketsContentContainer" class="collection">
                    <div id="TicketsHeaderContainer" class="ticketColumns collection-item">
                        <div style="width: 50%" class="ticketHeaderColumn">Описание</div>
                        <div style="width: 25%" class="ticketHeaderColumn">Цена</div>
                        <div style="width: 25%" class="ticketHeaderColumn">Количество</div>
                    </div>
                    <div id="TicketsListContainer">
                        @foreach (TicketModel ticket in Model.Tickets)
                        {
                            await Html.RenderPartialAsync("Ticket", new TicketViewModel
                            {
                                Ticket = ticket,
                                CanEdit = Model.CanEditTickets,
                                ReturnUrl = Model.ReturnUrlToHome
                            });
                        }
                    </div>
                </div>
                <div id="PaginationContainer" class="pagination-container">
                    <div pagination-data="@Model.PaginationData" page-action="Index" route-values="@routeValues" class="pages-container"></div>
                    <div class="items-per-page-container">
                        <div style="float: left">Количество записей на странице:&nbsp;</div>
                        <div items-per-pages="@Model.ItemsPerPages" action="Index" route-values="@routeValues" style="float: left"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>